title: RiverLife Bible Reading Plan #----> Required
remote_theme: wharrf/brp-theme
timezone: Asia/Singapore
repository: Buooy/Opendoc #----> Required
plugins:
  - jekyll-seo-tag
  - jekyll-include-cache
baseurl: ''
permalink: '/:path/:basename'
logo: /assets/logo.png
image: /assets/logo.png
server_PROD: https://search.opendoc.sg
server_DEV: https://search-staging.opendoc.sg
google_analytics:  '164700690-1' #----> Optional, Google analytics ID

fast_build: false
offline: true
preload_pages: true

styling_options:
  primary_brand_color: '#3eaf7c'  #----> Optional, theme color
  logo_path: /assets/logo.png  #----> Optional, path to logo
  opendoc_logo_path: /assets/images/logo-full.png
  feedback_url: mailto:aaron.lee@buooy.com #----> Optional, feedback url
  
folders:
  - name: 'week-16'
    title: 'Week 16'
    order:
      - index.md
  - name: 'week-15'
    title: 'Week 15'
    order:
      - index.md
  - name: 'week-14'
    title: 'Week 14'
    order:
      - index.md
  - name: 'week-13'
    title: 'Week 13'
    order:
      - index.md
  - name: 'week-12'
    title: 'Week 12'
    order:
      - index.md
  - name: 'week-11'
    title: 'Week 11'
    order:
      - index.md
  - name: 'week-10'
    title: 'Week 10'
    order:
      - index.md
  - name: 'week-9'
    title: 'Week 9'
    order:
      - index.md
  - name: 'week-8'
    title: 'Week 8'
    order:
      - index.md
  - name: 'week-7'
    title: 'Week 7'
    order:
      - index.md
  - name: 'week-6'
    title: 'Week 6'
    order:
      - index.md
  - name: 'week-5'
    title: 'Week 5'
    order:
      - index.md
  - name: 'week-4'
    title: 'Week 4'
    order:
      - index.md
  - name: 'week-3'
    title: 'Week 3'
    order:
      - index.md
  - name: 'week-2'
    title: 'Week 2'
    order:
      - index.md
  - name: 'week-1'
    title: 'Week 1'
    order:
      - index.md
